version: "3.8"
services:   
  backend:
    build: ./server
    container_name: server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
  
  client:
    build: ./client
    container_name: client
    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
