enum ActionType {
    VALIDATE_INPUT = "VALIDATE_INPUT",
    CLEAR_ALERT = "CLEAR_ALERT",
    AUTH_USER_BEGIN = "LOGIN_USER_BEGIN",
    AUTH_USER_SUCCESS = "LOGIN_USER_SUCCESS",
    AUTH_USER_FAILED= "LOGIN_USER_FAILED",

    GET_QUIZ_BEGIN= "GET_QUIZ_BEGIN",
    GET_QUIZ_SUCCESS="GET_QUIZ_SUCCESS",

    GET_SINGLE_QUIZ_BEGIN= "GET_SINGLE_QUIZ_BEGIN",
    GET_SINGLE_QUIZ_SUCCESS="GET_SINGLE_QUIZ_SUCCESS",
    GET_SINGLE_QUIZ_FAILED="GET_SINGLE_QUIZ_FAILED",

    MANAGE_SINGLE_QUIZ_START="MANAGE_SINGLE_QUIZ_START",
    MANAGE_SINGLE_QUIZ_END="MANAGE_SINGLE_QUIZ_END",

    GET_QUIZ_QUESTIONS_SUCCESS="GET_QUIZ_QUESTIONS_SUCCESS",

    EDIT_QUIZ="EDIT_QUIZ",

    SET_QUESTION_TYPE="SET_QUESTION_TYPE"
}

export default ActionType