enum ActionType {
    VALIDATE_INPUT = "VALIDATE_INPUT",
    CLEAR_ALERT = "CLEAR_ALERT",
    AUTH_USER_BEGIN = "LOGIN_USER_BEGIN",
    AUTH_USER_SUCCESS = "LOGIN_USER_SUCCESS",
    AUTH_USER_FAILED= "LOGIN_USER_FAILED",

    GET_QUIZ_BEGIN= "GET_QUIZ_BEGIN",
    GET_QUIZ_SUCCESS="GET_QUIZ_SUCCESS",

    GET_SINGLE_QUIZ_BEGIN= "GET_SINGLE_QUIZ_BEGIN",
    GET_SINGLE_QUIZ_SUCCESS="GET_SINGLE_QUIZ_SUCCESS",
    GET_SINGLE_QUIZ_FAILED="GET_SINGLE_QUIZ_FAILED",

    MANAGE_SINGLE_QUIZ_START="MANAGE_SINGLE_QUIZ_START",
    MANAGE_SINGLE_QUIZ_END="MANAGE_SINGLE_QUIZ_END",

    GET_QUIZ_QUESTIONS_SUCCESS="GET_QUIZ_QUESTIONS_SUCCESS",

    EDIT_QUIZ_BEGIN="EDIT_QUIZ_BEGIN",
    EDIT_QUIZ_SUCCESS="EDIT_QUIZ_SUCCESS",

    EXECUTE_EDIT_QUIZ_BEGIN="EXECUTE_EDIT_QUIZ_BEGIN",
    EXECUTE_EDIT_QUIZ_SUCCESS="EXECUTE_EDIT_QUIZ_SUCCESS",
    EXECUTE_EDIT_QUIZ_FAILED="EXECUTE_EDIT_QUIZ_FAILED",

    DELETE_QUIZ_BEGIN="DELETE_QUIZ_BEGIN",
    DELETE_QUIZ_SUCCESS="DELETE_QUIZ_SUCCESS",
    DELETE_QUIZ_FAILED="DELETE_QUIZ_FAILED",

    SET_QUESTION_TYPE="SET_QUESTION_TYPE",
    SET_EDIT_QUESTION="SET_EDIT_QUESTION",
    CANCEL_EDIT_QUESTION="CANCEL_EDIT_QUESTION"
}

export default ActionType